# Generated by Django 5.1.5 on 2025-02-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='time_in',
            field=models.DateTimeField(auto_now_add=True, default='2025-02-03 15:04:41.704211'),
            preserve_default=False,
        ),
    ]
